### ISSUE TITLE
error ng-recaptcha angular 11.0.4

### ISSUE THREAD

**Issue by anthonyjuarezsolis** [DethAriel/ng-recaptcha#249]
package.json 
  "dependencies": {
    "@angular/animations": "~11.0.4",
    "@angular/cdk": "^11.2.13",
    "@angular/common": "~11.0.4",
    "@angular/compiler": "~11.0.4",
    "@angular/core": "~11.0.4",
    "@angular/forms": "~11.0.4",
    "@angular/localize": "^12.0.0",
    "@angular/material": "^11.0.3",
    "@angular/platform-browser": "~11.0.4",
    "@angular/platform-browser-dynamic": "~11.0.4",
    "@angular/router": "~11.0.4",
    "@ng-bootstrap/ng-bootstrap": "^9.1.1",
    "@ng-idle/core": "^11.1.0",
    "@ng-idle/keepalive": "^11.0.3",
    "@rxweb/reactive-form-validators": "^2.1.3",
    "amplitude-js": "^8.1.0",
    "angular2-moment": "^1.9.0",
    "angular2-text-mask": "^9.0.0",
    "chart.js": "^2.9.4",
    "moment": "^2.29.1",
    "ng-intercom": "^8.0.2",
    "ng-recaptcha": "^9.0.0",
    "ng2-charts": "^2.4.2",
    "ngx-highlight-js": "^13.0.0",
    "primeicons": "4.1.0",
    "primeng": "9.0.1",
    "rxjs": "~6.6.3",
    "text-mask-addons": "^3.8.0",
    "tslib": "^2.0.3",
    "zone.js": "~0.11.3"
  },

console error

Error: node_modules/ng-recaptcha/lib/recaptcha-common.module.d.ts:4:21 - error TS2694: Namespace '"C:/Users/antho/Desktop/anthony/Nueva carpeta/Proyectos/ontop/top-web-v2/node_modules/@angular/core/core"' has no exported member 'ɵɵFactoryDeclaration'.

4     static ɵfac: i0.ɵɵFactoryDeclaration<RecaptchaCommonModule, never>;
                      ~~~~~~~~~~~~~~~~~~~~
node_modules/ng-recaptcha/lib/recaptcha-common.module.d.ts:5:21 - error TS2694: Namespace '"C:/Users/antho/Desktop/anthony/Nueva carpeta/Proyectos/ontop/top-web-v2/node_modules/@angular/core/core"' has no exported member 'ɵɵNgModuleDeclaration'.

5     static ɵmod: i0.ɵɵNgModuleDeclaration<RecaptchaCommonModule, [typeof i1.RecaptchaComponent], never, [typeof i1.RecaptchaComponent]>;
                      ~~~~~~~~~~~~~~~~~~~~~
node_modules/ng-recaptcha/lib/recaptcha-common.module.d.ts:6:21 - error TS2694: Namespace '"C:/Users/antho/Desktop/anthony/Nueva carpeta/Proyectos/ontop/top-web-v2/node_modules/@angular/core/core"' has no exported member 'ɵɵInjectorDeclaration'.

6     static ɵinj: i0.ɵɵInjectorDeclaration<RecaptchaCommonModule>;
                      ~~~~~~~~~~~~~~~~~~~~~
node_modules/ng-recaptcha/lib/recaptcha-forms.module.d.ts:6:21 - error TS2694: Namespace '"C:/Users/antho/Desktop/anthony/Nueva carpeta/Proyectos/ontop/top-web-v2/node_modules/@angular/core/core"' has no exported member 'ɵɵFactoryDeclaration'.

6     static ɵfac: i0.ɵɵFactoryDeclaration<RecaptchaFormsModule, never>;
                      ~~~~~~~~~~~~~~~~~~~~
node_modules/ng-recaptcha/lib/recaptcha-forms.module.d.ts:7:21 - error TS2694: Namespace '"C:/Users/antho/Desktop/anthony/Nueva carpeta/Proyectos/ontop/top-web-v2/node_modules/@angular/core/core"' has no exported member 'ɵɵNgModuleDeclaration'.

7     static ɵmod: i0.ɵɵNgModuleDeclaration<RecaptchaFormsModule, [typeof i1.RecaptchaValueAccessorDirective], [typeof i2.FormsModule, typeof i3.RecaptchaCommonModule], [typeof i1.RecaptchaValueAccessorDirective]>;
                      ~~~~~~~~~~~~~~~~~~~~~
node_modules/ng-recaptcha/lib/recaptcha-forms.module.d.ts:8:21 - error TS2694: Namespace '"C:/Users/antho/Desktop/anthony/Nueva carpeta/Proyectos/ontop/top-web-v2/node_modules/@angular/core/core"' has no exported member 'ɵɵInjectorDeclaration'.

8     static ɵinj: i0.ɵɵInjectorDeclaration<RecaptchaFormsModule>;
                      ~~~~~~~~~~~~~~~~~~~~~
node_modules/ng-recaptcha/lib/recaptcha-loader.service.d.ts:23:21 - error TS2694: Namespace '"C:/Users/antho/Desktop/anthony/Nueva carpeta/Proyectos/ontop/top-web-v2/node_modules/@angular/core/core"' has no exported member 'ɵɵFactoryDeclaration'.

23     static ɵfac: i0.ɵɵFactoryDeclaration<RecaptchaLoaderService, [null, { optional: true; }, { optional: true; }, { optional: true; }, { optional: true; }]>;
91m                       ~~~~~~~~~~~~~~~~~~~~
node_modules/ng-recaptcha/lib/recaptcha-loader.service.d.ts:24:22 - error TS2694: Namespace '"C:/Users/antho/Desktop/anthony/Nueva carpeta/Proyectos/ontop/top-web-v2/node_modules/@angular/core/core"' has no exported member 'ɵɵInjectableDeclaration'.

24     static ɵprov: i0.ɵɵInjectableDeclaration<RecaptchaLoaderService>;
                        ~~~~~~~~~~~~~~~~~~~~~~~
node_modules/ng-recaptcha/lib/recaptcha-v3.module.d.ts:3:21 - error TS2694: Namespace '"C:/Users/antho/Desktop/anthony/Nueva carpeta/Proyectos/ontop/top-web-v2/node_modules/@angular/core/core"' has no exported member 'ɵɵFactoryDeclaration'.

3     static ɵfac: i0.ɵɵFactoryDeclaration<RecaptchaV3Module, never>;
                      ~~~~~~~~~~~~~~~~~~~~
node_modules/ng-recaptcha/lib/recaptcha-v3.module.d.ts:4:21 - error TS2694: Namespace '"C:/Users/antho/Desktop/anthony/Nueva carpeta/Proyectos/ontop/top-web-v2/node_modules/@angular/core/core"' has no exported member 'ɵɵNgModuleDeclaration'.

4     static ɵmod: i0.ɵɵNgModuleDeclaration<RecaptchaV3Module, never, never, never>;
                      ~~~~~~~~~~~~~~~~~~~~~
node_modules/ng-recaptcha/lib/recaptcha-v3.module.d.ts:5:21 - error TS2694: Namespace '"C:/Users/antho/Desktop/anthony/Nueva carpeta/Proyectos/ontop/top-web-v2/node_modules/@angular/core/core"' has no exported member 'ɵɵInjectorDeclaration'.

5     static ɵinj: i0.ɵɵInjectorDeclaration<RecaptchaV3Module>;
                      ~~~~~~~~~~~~~~~~~~~~~
node_modules/ng-recaptcha/lib/recaptcha-v3.service.d.ts:76:21 - error TS2694: Namespace '"C:/Users/antho/Desktop/anthony/Nueva carpeta/Proyectos/ontop/top-web-v2/node_modules/@angular/core/core"' has no exported member 'ɵɵFactoryDeclaration'.

76     static ɵfac: i0.ɵɵFactoryDeclaration<ReCaptchaV3Service, [null, null, null, { optional: true; }, { optional: true; }, { optional: true; }]>;
                       ~~~~~~~~~~~~~~~~~~~~
node_modules/ng-recaptcha/lib/recaptcha-v3.service.d.ts:77:22 - error TS2694: Namespace '"C:/Users/antho/Desktop/anthony/Nueva carpeta/Proyectos/ontop/top-web-v2/node_modules/@angular/core/core"' has no exported member 'ɵɵInjectableDeclaration'.

77     static ɵprov: i0.ɵɵInjectableDeclaration<ReCaptchaV3Service>;
                        ~~~~~~~~~~~~~~~~~~~~~~~
node_modules/ng-recaptcha/lib/recaptcha-value-accessor.directive.d.ts:16:21 - error TS2694: Namespace '"C:/Users/antho/Desktop/anthony/Nueva carpeta/Proyectos/ontop/top-web-v2/node_modules/@angular/core/core"' has no exported member 'ɵɵFactoryDeclaration'.

16     static ɵfac: i0.ɵɵFactoryDeclaration<RecaptchaValueAccessorDirective, never>;
                       ~~~~~~~~~~~~~~~~~~~~
node_modules/ng-recaptcha/lib/recaptcha-value-accessor.directive.d.ts:17:21 - error TS2694: Namespace '"C:/Users/antho/Desktop/anthony/Nueva carpeta/Proyectos/ontop/top-web-v2/node_modules/@angular/core/core"' has no exported member 'ɵɵDirectiveDeclaration'.

17     static ɵdir: i0.ɵɵDirectiveDeclaration<RecaptchaValueAccessorDirective, "re-captcha[formControlName],re-captcha[formControl],re-captcha[ngModel]", never, {}, {}, never>;
                       ~~~~~~~~~~~~~~~~~~~~~~
node_modules/ng-recaptcha/lib/recaptcha.component.d.ts:58:21 - error TS2694: Namespace '"C:/Users/antho/Desktop/anthony/Nueva carpeta/Proyectos/ontop/top-web-v2/node_modules/@angular/core/core"' has no exported member 'ɵɵFactoryDeclaration'.

58     static ɵfac: i0.ɵɵFactoryDeclaration<RecaptchaComponent, [null, null, null, { optional: true; }]>;
                       ~~~~~~~~~~~~~~~~~~~~
node_modules/ng-recaptcha/lib/recaptcha.component.d.ts:59:21 - error TS2694: Namespace '"C:/Users/antho/Desktop/anthony/Nueva carpeta/Proyectos/ontop/top-web-v2/node_modules/@angular/core/core"' has no exported member 'ɵɵComponentDeclaration'.

59     static ɵcmp: i0.ɵɵComponentDeclaration<RecaptchaComponent, "re-captcha", ["reCaptcha"], { "id": "id"; "siteKey": "siteKey"; "theme": "theme"; "type": "type"; "size": "size"; "tabIndex": "tabIndex"; "badge": "badge"; "errorMode": "errorMode"; }, { "resolved": "resolved"; "error": "error"; }, never, never>;
                       ~~~~~~~~~~~~~~~~~~~~~~
node_modules/ng-recaptcha/lib/recaptcha.module.d.ts:5:21 - error TS2694: Namespace '"C:/Users/antho/Desktop/anthony/Nueva carpeta/Proyectos/ontop/top-web-v2/node_modules/@angular/core/core"' has no exported member 'ɵɵFactoryDeclaration'.

5     static ɵfac: i0.ɵɵFactoryDeclaration<RecaptchaModule, never>;
                      ~~~~~~~~~~~~~~~~~~~~
node_modules/ng-recaptcha/lib/recaptcha.module.d.ts:6:21 - error TS2694: Namespace '"C:/Users/antho/Desktop/anthony/Nueva carpeta/Proyectos/ontop/top-web-v2/node_modules/@angular/core/core"' has no exported member 'ɵɵNgModuleDeclaration'.

6     static ɵmod: i0.ɵɵNgModuleDeclaration<RecaptchaModule, never, [typeof i1.RecaptchaCommonModule], [typeof i2.RecaptchaComponent]>;
                      ~~~~~~~~~~~~~~~~~~~~~
node_modules/ng-recaptcha/lib/recaptcha.module.d.ts:7:21 - error TS2694: Namespace '"C:/Users/antho/Desktop/anthony/Nueva carpeta/Proyectos/ontop/top-web-v2/node_modules/@angular/core/core"' has no exported member 'ɵɵInjectorDeclaration'.

7     static ɵinj: i0.ɵɵInjectorDeclaration<RecaptchaModule>;
                      ~~~~~~~~~~~~~~~~~~~~~

**Comment by banana-bread** [comment]
+1

**Comment by anthonyjuarezsolis** [comment]
Try downloading the ng recapcha version from 9 to 8 and it worked, it doesn’t be the right way but it works!

**Comment by anthonyjuarezsolis** [comment]
> 1

**Comment by Fijo** [comment]
I ran into the same issue - the latest version that works with angular 11 is 8.0.1

**Comment by alih12345** [comment]
+1

**Comment by DethAriel** [comment]
hey folks! Apologies for any confusion this has caused. As was stated in the [changelog for v7.0.0](https://github.com/DethAriel/ng-recaptcha/blob/master/CHANGELOG.md#700-2020-12-22):

> [...] Add Angular 11 support
> [...]
> [...] Support for previous versions of Angular has been dropped. Starting from v7 only one version of Angular will be supported

So the only version of `ng-recaptcha` that supports Angular 11 is, hence, the `v7.x.x` branch.

In the future I will try to be more explicit with this, stating the drop of the previous Angular version support in the changelog.
